lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  projects:
    order:
      - sscl.md
      - gg.md
      - jackbox.md
      - ucla.md
      - heatsig.md